# Generated by Django 3.1.12 on 2024-12-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_youtube'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='game',
        #     table='game',
        # ),
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_analysis', models.JSONField(default=list)),
                ('all_analysis', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_analysis', to='functions.game')),
            ],
            options={
                'db_table': 'steam_game_reviewanalysis',
            },
        ),
    ]
