# Generated by Django 3.1.12 on 2024-12-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_auto_20241217_1022'),
    ]

    operations = [
    ]
