# Generated by Django 3.1.12 on 2024-12-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_auto_20241217_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
